### ISSUE TITLE
declare file encoding

### ISSUE THREAD

**Issue by paulignari** [mosra/m.css#17] opened 2017-12-03 15:33 UTC
In my environment (debian 9, pelican 3.7.1 from debian package), `pelican content` complains about `Non-ASCII character '\xc2' in file`, due UTF8 characters in copyright statement.

Prepending a charset declaration to python files let's thing woks for all files except for htmlsanity.py, so I made pull request #15 with my patch.

The file htmlsanity.py has another trouble with python 2.7:

`CRITICAL: TypeError: ord() expected a character, but string of length 6 found`

due this line:

`ord('\u00AD'): '&shy;'}`

but I don't know how to deal with it.

**Comment by mosra** [comment] 2017-12-04 10:08
Hi, sorry to disappoint, but unfortunately I don't have the capacity to maintain compatibility with both Python 2 and Python 3 so I decided to make the project exclusive to Python 3. The encoding is only a small part of the problem -- some of the plugins wouldn't work on Python 2 at all because the differences between Py2 and Py3 APIs are too large. Sorry.

The documentation mentions this, but not visibly enough. I'll update that.

Would it be possible for you to use a Python 3 version of Pelican? For example, using `pip3`:

```sh
pip3 install pelican # maybe sudo?
```

(Yes, I know all the implications of using `pip` instead of a system package, but as far as I know, Debian does not provide a Python 3 package for Pelican yet: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=875255 . Hopefully that changes in the future.)

**Comment by paulignari** [comment] 2017-12-04 16:16
I understand you and I cannot ask you to maintain backwards compatibility with python2.

When I had troubles with plug-in, I found articles stating I'll need a character encoding declaration due https://www.python.org/dev/peps/pep-0263/, so I thought that single line may be valid even for python3.

I'm reluctant not to use the debian package, for a series of good administrative practices, so I tried to advocate re-packaging pelican with python3 in https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=875255#10

If it does not work I will decide whether to keep the fork I'm using now or if I go to the installation via pip.

**Comment by mosra** [comment] 2017-12-04 18:26
> so I thought that single line may be valid even for python3

Yes, that's true, but the problem is that with new files added I may forget to add it and unless I will be putting extra effort into testing everything with python2, the compatibility will get broken again. I don't have the capacity for that extra effort at the moment and having half-broken Python2 support is worse than having none, I think.

> I'm reluctant not to use the debian package, for a series of good administrative practices

Yes, I know. What could be done is modifying the package source and build a package depending on Python 3 from it. As far as I can see, it could be just a matter of replacing `python-*` packages with `python3-*` in the `control` file and `python2` with `python3` in the `rules` file. But I don't have any access to a Debian system to check that myself. In fact, it would be easier for me to just provide a Python3-based Debian package of Pelican than test and backport for Python2 ;)

There's version 3.8.0 of Pelican soon to be released (waiting for it myself), so hopefully Debian maintainers reconsider Python 3 during the update.

The following line:

> ```py
> ord('\u00AD'): '&shy;'}
> ```

could be replaced with:

> ```py
> ord(u'\u00AD'): '&shy;'}
> ```

to make it work under Python 2, I think.

In 78161a0b1b25e3e234411726c4faada9e1ef97be I made it clearer that Python 3 is required. So if you are fine with this at the moment, I vote for closing this issue :)

**Comment by paulignari** [comment] 2017-12-04 18:36
Thanks for suggestions.


You can close this issue, as going with python3 is the right thing to 
do. I'll try to see how to deal with this.


-- 

Mandi.

Paolo

**Comment by mosra** [comment] 2017-12-04 18:55
Great :)

**Closed by mosra** 2017-12-04 18:55 UTC
