### ISSUE TITLE
C project specifics

### ISSUE THREAD

**Issue by ranebrown** [mosra/m.css#86] opened 2019-01-24 23:38 UTC
I'm attempting to use the Doxygen output for a C project (it looks like it was built with C++ in mind). Generally, things are working but I have a question related to the documentation of enums and structs. When I generate the documentation with stock Doxygen it creates a 'Globals' section with links to 'Functions', 'Variables', 'Enumerations', 'Macros'. Is there an easy way to get these same items to appear under the Modules menu?

I tried using groups - `\defgroup groupname` `\ingroup groupname` but using `ingroup` with an enum or struct caused errors when running the `doc2html5.py` script.

Any help would be appreciated!

**Comment by mosra** [comment] 2019-02-02 09:11
Yes, the project this was originally built for is in C++, but as far as I'm aware, it should work with C as well, the only difference being no docs generated for namespaces/classes.

You mean those Functions / ... appearing as an item in the top menu? Never saw that myself. Is that maybe related to the `OPTIMIZE_OUTPUT_FOR_C` option? From what I know, these sections are present, but only in a particular page for either a file or a module (well, or a namespace/class, but that's a C++ thing).

The theme also supports per-file documentation, if that would help you in any way. You just need to ensure every file has a toplevel `\file` documentation. More info [in the docs](https://mcss.mosra.cz/doxygen/#generated-output-is-mostly-empty).

Can you post what the errors were? Ideally with a a small code snippet that can reproduce them. Thank you!

**Comment by ranebrown** [comment] 2019-02-04 19:45
Here is a sample file and doxygen configuration. When generating the documentation with Doxygen you can go to Files -> Globals and see menu items for Functions, Enumerations etc. I was looking for a way to get those to appear under Modules using your theme. The documentation for these items is available on the page specific link but it is convenient to have them show up in the menu.
```C
/**
 * @file
 * @brief the main project file
 * @details detailed info here
 * @defgroup myenums Enumerations
 * @defgroup mystructs Structures
 * @defgroup mymacros Macros
 */

#include <stdio.h>
#include <stdlib.h>

/// @brief my macro description
/// @ingroup mymacros
#define MY_MACRO 1

/**
 * @enum values
 * @brief sample enum
 * @ingroup myenums
 */
typedef enum
{
    VALUE1, ///< first value
    VALUE2  ///< second value
} values;

/**
 * @struct mystruct
 * @brief test struct
 * @ingroup mystructs
 */
typedef struct
{
    int test1;       ///< test value
    int test2;       ///< another test value
} mystruct;

/**
 * @brief main entry
 * @details info
 * @returns 0 on success
 */
int main(void)
{
    printf("Hello World!\n");
    return 0;
}
```
```doxygen
PROJECT_NAME           = "Test Project"
PROJECT_BRIEF          = "Tagline"
FULL_PATH_NAMES        = NO
OPTIMIZE_OUTPUT_FOR_C  = YES
EXTRACT_STATIC         = YES
CASE_SENSE_NAMES       = YES
QUIET                  = YES
GENERATE_LATEX         = NO
TOC_INCLUDE_HEADINGS   = 4
```

I'm not sure what happened with the errors I was seeing. The above example using `@defgroup` and `@ingroup` seems to be working fine now. Previously I was getting an error related to this line `assert id.startswith(state.current_definition_url_base)` in your script. I commented it out at one point and everything was generated correctly. Now it seems to be working without commenting it out. I'm not sure if I changed something else in my config file or one of the source files.

**Comment by ranebrown** [comment] 2019-02-04 19:47
If I'm able to use custom groups correctly (which seem to be working now) then showing the items from the "Globals" menu isn't as big of a deal.

**Comment by mosra** [comment] 2019-02-07 09:11
Thanks for the detailed repro case! :+1: 

The assertion is sometimes happening when you have stale XML files in the output directory, as it then gets confused about the symbol hierarchy.

> When generating the documentation with Doxygen you can go to Files -> Globals and see menu items for Functions, Enumerations etc. I was looking for a way to get those to appear under Modules using your theme.

I'm quite busy right now so I can't look deeper into this, but I was thinking putting an explicit link to the navbar could be the solution? For example, completely off the top of my head (you may want to adapt the URLs):

```ini
M_LINKS_NAVBAR1 = \
    "<a href=\"group__myenums.html\">Enums</a>" \
    "<a href=\"group__mystructs.html\">Structures</a>" \
    "<a href=\"group__myfuncs.html\">Functions</a>"
```

Or, if you have everything in a single file without groups:

```ini
M_LINKS_NAVBAR1 = \
    "<a href=\"mylib_8h.html#enum-members\">Enums</a>" \
    "<a href=\"mylib_8h.html#nested-classes\">Structures</a>" \ 
    "<a href=\"mylib_8h.html#func-members\">Functions</a>"
```

There's also `M_LINKS_NAVBAR2`, defining the other half of the links (which is second column of the top navbar on small screens), so you might want to split the links between the two. You can also have submenus, see [the docs](https://mcss.mosra.cz/doxygen/#navbar-links) for details. Hope this is what you are after :)

**Comment by mosra** [comment] 2019-02-23 01:01
@ranebrown did the above suggestion work for you? :)

**Comment by ranebrown** [comment] 2019-02-23 21:24
Yep, between the groups working as expected and your navbar suggestion I'm able to have things show up how I want them.

The only other thing I have noticed is that the function summary for each section uses `auto` in the documentation which isn't valid for C. If possible it would be nice if that option was disabled when the `OPTIMIZE_OUTPUT_FOR_C` flag is in use. Not sure if this would mess up your style/formatting though.

Thanks!

**Comment by mosra** [comment] 2019-02-24 16:53
> the function summary for each section uses `auto` in the documentation which isn't valid for C

Would the suggestion in #91 work for you? I'm hesitant to make too many options affect the template because it makes it much harder to reliably test all combinations (and then the theme would end up being the same unmaintainable hell like the vanilla Doxygen output is).

**Comment by ranebrown** [comment] 2019-02-25 17:29
Modifying `entry-func.html` seems to work so far.

I changed

`{% if func.type == 'void' %}void {% elif func.type %}auto {% endif %}`

to

`{{ func.type }} ` (with trailing space)

and deleted

`{% if func.type and func.type != 'void' %} -&gt; {{ func.type }}{% endif %}`

Thanks for the help and the awesome theme!

**Comment by mosra** [comment] 2019-07-07 16:35
I think it's all done here? Closing :)

**Closed by mosra** 2019-07-07 16:35 UTC
